<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class VenueSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('venues')->insert([
            [
            'name' => 'Studio Foto Ditangguhkan 1',
            'status' => 0,
            'address' => 'Pauh',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang',
            'phone_number' => '08923478723',
            'picture' => 'studio1.jpg',
            'latitude' => -0.892292000,
            'longitude' => 100.327448000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditangguhkan 2',
            'status' => 0,
            'address' => 'Simp Pasia',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang',
            'phone_number' => '08923473423',
            'picture' => 'studio2.jpg',
            'latitude' => -0.8934292000,
            'longitude' => 100.327448000,
            'reject_note' => '',
            'owner_id' => 2,
            ],
            [
            'name' => 'Studio Foto Ditangguhkan 3',
            'status' => 0,
            'address' => 'Limau Manis',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang',
            'phone_number' => '08923473423',
            'picture' => 'studio3.jpg',
            'latitude' => -0.8934292000,
            'longitude' => 100.327448000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditangguhkan 4',
            'status' => 0,
            'address' => 'Unand',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang',
            'phone_number' => '08923473423',
            'picture' => 'studio1.jpg',
            'latitude' => -0.8934292000,
            'longitude' => 100.327448000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Diterima 1',
            'status' => 1,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478753',
            'picture' => 'studio2.jpg',
            'latitude' => -0.898336000,
            'longitude' => 100.355960000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Diterima 2',
            'status' => 1,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478753',
            'picture' => 'studio2.jpg',
            'latitude' => -0.898336000,
            'longitude' => 100.355960000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Diterima 3',
            'status' => 1,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478753',
            'picture' => 'studio2.jpg',
            'latitude' => -0.898336000,
            'longitude' => 100.355960000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Diterima 4',
            'status' => 1,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478753',
            'picture' => 'studio2.jpg',
            'latitude' => -0.898336000,
            'longitude' => 100.355960000,
            'reject_note' => '',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditolak 1',
            'status' => 2,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478752',
            'picture' => 'studio3.jpg',
            'latitude' => -0.875730000,
            'longitude' => 100.384948000,
            'reject_note' => 'tidak ada surat IMB',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditolak 2',
            'status' => 2,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478752',
            'picture' => 'studio3.jpg',
            'latitude' => -0.875730000,
            'longitude' => 100.384948000,
            'reject_note' => 'tidak ada surat IMB',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditolak 3',
            'status' => 2,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478752',
            'picture' => 'studio3.jpg',
            'latitude' => -0.875730000,
            'longitude' => 100.384948000,
            'reject_note' => 'tidak ada surat IMB',
            'owner_id' => 1,
            ],
            [
            'name' => 'Studio Foto Ditolak 4',
            'status' => 2,
            'address' => 'Padang, Sumatera Barat',
            'imb' => 'contoh_imb.pdf',
            'information' => 'Studio foto di daerah padang B',
            'phone_number' => '08923478752',
            'picture' => 'studio3.jpg',
            'latitude' => -0.875730000,
            'longitude' => 100.384948000,
            'reject_note' => 'tidak ada surat IMB',
            'owner_id' => 1,
            ],


        ]);
    }
}
